server:
  port: 9999

spring:
  application:
    name: springboot-demo
  jpa:
    show-sql: true
    open-in-view: false
  jooq:
    sql-dialect: h2
  main:
    allow-bean-definition-overriding: true

