server:
  port: 9999

spring:
  application:
    name: springboot-thymeleaf-demo
  jpa:
    show-sql: true
    open-in-view: false
  jooq:
    sql-dialect: h2
  main:
    allow-bean-definition-overriding: true

# 启动可以看springboot启动的详细的log，用于排错使用
#debug: true
